### ISSUE TITLE
No messages

### ISSUE THREAD

**Issue by rutsky** [gerchardon/docker-logio#4]
I installed docker-logion according instructions from README:

```
docker run -d --name logio -p 28777:28777 -p 28778:28778 temal/logio-server
docker run -d --privileged --link logio:logio -v /var/run/docker.sock:/var/run/docker.sock gerchardon/docker-logio -n `uname -n` -h logio
```

Now at http://localhost:28778 I see streams from all docker containers, but no messages (I knew that new messages are generating, because I see new messages in `docker logs some-container`).

Environment: Ubuntu 14.04 with Docker 1.8.2, all images pulled just now.

```
# docker logs logio
info: socket.io started
```

```
# docker logs angry_mccarthy # container with docker-logio
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DestroyableTransform.addListener (events.js:160:15)
    at DestroyableTransform.Readable.on (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:729:33)
    at DestroyableTransform.once (events.js:185:8)
    at DestroyableTransform.Readable.pipe (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:581:8)
    at EventEmitter.attachContainer (/usr/src/app/node_modules/docker-loghose/loghose.js:60:7)
    at EventEmitter.emit (events.js:117:20)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:56:16
    at Array.forEach (native)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:55:18
    at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:201:5
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DestroyableTransform.addListener (events.js:160:15)
    at DestroyableTransform.Readable.on (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:729:33)
    at DestroyableTransform.Readable.pipe (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at EventEmitter.attachContainer (/usr/src/app/node_modules/docker-loghose/loghose.js:60:7)
    at EventEmitter.emit (events.js:117:20)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:56:16
    at Array.forEach (native)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:55:18
    at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:201:5
    at Modem.buildPayload (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:222:7)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DestroyableTransform.addListener (events.js:160:15)
    at DestroyableTransform.Readable.on (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:729:33)
    at DestroyableTransform.Readable.pipe (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:8)
    at EventEmitter.attachContainer (/usr/src/app/node_modules/docker-loghose/loghose.js:60:7)
    at EventEmitter.emit (events.js:117:20)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:56:16
    at Array.forEach (native)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:55:18
    at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:201:5
    at Modem.buildPayload (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:222:7)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DestroyableTransform.addListener (events.js:160:15)
    at DestroyableTransform.Readable.on (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:729:33)
    at DestroyableTransform.once (events.js:185:8)
    at DestroyableTransform.Readable.pipe (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:576:8)
    at EventEmitter.attachContainer (/usr/src/app/node_modules/docker-loghose/loghose.js:60:7)
    at EventEmitter.emit (events.js:117:20)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:56:16
    at Array.forEach (native)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:55:18
    at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:201:5
```

How can I debug why it's not working?

**Comment by gerchardon** [comment]
It's a warning for memory leak but it's work see https://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n

Docker 1.8 need newer dependencies to see log (I will commit package.json with update dependencies)

If you want to debug it or run in standalone mode :

```
git clone https://github.com/gerchardon/docker-logio.git
cd docker-logio
npm install
node index.js
```

**Comment by gerchardon** [comment]
New Version with fix v0.3.0 (npm ready , docker hub soon)

**Comment by rutsky** [comment]
I tested 0.3.0 --- it works, thanks for such quick response, @gerchardon!

**Comment by rutsky** [comment]
By the way: it doesn't work on Docker version 1.7.1.
Fails with:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

Not sure if you should support older Docker versions.

**Comment by rutsky** [comment]
> By the way: it doesn't work on Docker version 1.7.1.

I had error in my configuration, looks like it should work, sorry for the noise.
